services:
  # -----------------------------------------------
  # --- LOCAL DEVELOPMENT SERVICES (No Firebase)
  # -----------------------------------------------
  js-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: js-dev
    container_name: reader-js-local
    command: npm run serve
    volumes:
      - ./js:/app/js
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    profiles: ["dev"]

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: python-dev
    container_name: reader-python-dev
    command: python /app/py/app.py basic
    environment:
      - DEV_SKIP_TOOL_CHECK=1
      - DEV_SKIP_NPM=1
      - READER_BASE_URL=http://js-server:3000
    volumes:
      - ./py:/app/py
      - ./config.yaml:/app/config.yaml
    ports:
      - "5001:5000"
    profiles: ["dev"]

  js-test:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: js-dev
    container_name: reader-js-test-runner
    command: ["bash", "-lc", "cd /app/js && npm run test:precompile-cjs"]
    working_dir: /app/js
    profiles: ["dev"]
    volumes:
      - ./js:/app/js
      - ./logs:/app/logs
    environment:
      - NODE_ENV=test
      - CI=true
      - SMART_TEST_CLEANUP=true

  # -----------------------------------------------
  # --- PRODUCTION PROFILE SERVICE
  # -----------------------------------------------
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: js-prod
    container_name: reader-server-prod
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
    profiles: ["prod"]