services:
  # -----------------------------------------------
  # --- LOCAL DEVELOPMENT SERVICES (No Firebase)
  # -----------------------------------------------
  js-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      target: js-dev
    container_name: reader-js-local
    command: npm run serve
    volumes:
      - ./js:/app/js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    profiles: ["dev"]

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      target: python-dev
    container_name: reader-python-dev
    command: python /app/py/app.py serve
    volumes:
      - ./py:/app/py
      - ./config.yaml:/app/config.yaml
    ports:
      - "5000:5000"
    profiles: ["dev"]

  js-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      target: js-dev
    container_name: reader-js-test-runner
    command: ./test-smart.sh
    working_dir: /app/js
    profiles: ["dev"]
    volumes:
      - ./js:/app/js
      - ./logs:/app/logs
    environment:
      - NODE_ENV=test
      - CI=true
      - SMART_TEST_CLEANUP=true

  # -----------------------------------------------
  # --- PRODUCTION PROFILE SERVICE
  # -----------------------------------------------
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reader-server-prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    profiles: ["prod"]