version: '3.8'

services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/local-storage
      - ./config.yaml:/app/config.yaml
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
      # Configuration via environment variables (fallback to config.yaml)
      RESPECT_ROBOTS_TXT: "true"
      ENABLE_PDF_PARSING: "true"
      ALLOW_ALL_TLDS: "false"
      DEBUG_MODE: "false"
    command: node build/server.js