[project]
name = "dearreader"
version = "0.1.0"
description = "Web content extraction and processing pipeline"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyyaml>=6.0",
    "requests>=2.25.0",
]

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.0",
]
