FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY py/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# The rest will be mounted as volumes
CMD ["python", "py/app.py", "serve"]